### ISSUE TITLE
Changing Preset's doesn't load preset

### ISSUE THREAD

**Issue by alcomposer** [greatest-ape/OctaSine#13]
**Describe the bug**
When editing a patch, and moving to another preset and back again, the GUI changes back to the original patch- but the plugin doesn't load the settings.

**What did you try to do**
Design a patch with OctaSine 001 preset, move to 002 preset, move back to 001, OctaSine doesn't load the settings back

**Expected behavior**
For OctaSine to load the patch not only visually but in the sound engine

**Software (please complete the following information):**
 - OctaSine version v0.5.1 (064f3dc)
 - DAW [Ardour 6.6.234 GIT]
 - OS: [Arch 5.12.13-arch1-2]

**Comment by greatest-ape** [comment]
@alcomposer 

Thanks!

I've implemented a fix in #14. Could you please checkout branch [preset-fixes](https://github.com/greatest-ape/OctaSine/tree/preset-fixes), build and try again?

**Comment by alcomposer** [comment]
Tested the preset-fixes and works now.
