### ISSUE TITLE
CLAP plugin

### ISSUE THREAD

**Issue by josb** [greatest-ape/OctaSine#133]
Would be nice to have a [CLAP](https://u-he.com/community/clap/)  plugin version.

**Comment by valsteen** [comment]
I just saw this on reddit, great stuff, and was about to suggest the same, I understand that's probably a lot of work. Maybe have a look at this rust framework supporting VST3 and Clap: https://github.com/robbert-vdh/nih-plug/ .

**Comment by josb** [comment]
Nice. In particular, that builds on top of https://github.com/glowcoil/clap-sys, which seems to implement the low-level CLAP interface.

**Comment by greatest-ape** [comment]
@josb @valsteen I've done a first implementation. Could you please try out the build for your preferred OS and check if you come across any issues?

[OctaSine-tmp-2023-01-30-Windows.zip](https://github.com/greatest-ape/OctaSine/files/10535573/OctaSine-tmp-2023-01-30-Windows.zip)
[OctaSine-tmp-2023-01-30-Ubuntu-20_04.zip](https://github.com/greatest-ape/OctaSine/files/10535574/OctaSine-tmp-2023-01-30-Ubuntu-20_04.zip)
[OctaSine-tmp-2023-01-30-macOS.zip](https://github.com/greatest-ape/OctaSine/files/10535575/OctaSine-tmp-2023-01-30-macOS.zip)

**Comment by greatest-ape** [comment]
Regarding nih-plug, if I started development on a new plugin now, I would use it, but I can't switch to it without breaking backwards compatibility.

**Comment by greatest-ape** [comment]
I'm going to close this now since I've merged support.

**Comment by josb** [comment]
Thanks for adding this, @greatest-ape! I'll test it soon.

**Comment by greatest-ape** [comment]
Great!
