### ISSUE TITLE
Runtime error while using on Reaper

### ISSUE THREAD

**Issue by Exink** [greatest-ape/OctaSine#134]
Hello,

I tried to open the latest version of OctaSine using Reaper 6.71, but I got the following error.

![Screen capture](https://user-images.githubusercontent.com/80442299/209740211-f99d30d1-3c68-426b-943c-752e7948165c.png)

And here is the log after this happens:

[OctaSine.log](https://github.com/greatest-ape/OctaSine/files/10311363/OctaSine.log)

Note that the previous version I had (0.8.1) was working alright, so I'm not exactly sure what's causing this issue.

Hope you can help me to solve this!

Thanks a lot.

**Comment by greatest-ape** [comment]
Thanks,

I've opened an issue in the iced repo: https://github.com/iced-rs/iced/issues/1625

**Comment by greatest-ape** [comment]
Could you please try this build?

[OctaSine-tmp-2023-01-01-Windows.zip](https://github.com/greatest-ape/OctaSine/files/10329324/OctaSine-tmp-2023-01-01-Windows.zip)
[OctaSine-tmp-2023-01-01-Ubuntu-20_04.zip](https://github.com/greatest-ape/OctaSine/files/10329325/OctaSine-tmp-2023-01-01-Ubuntu-20_04.zip)
[OctaSine-tmp-2023-01-01-macOS.zip](https://github.com/greatest-ape/OctaSine/files/10329326/OctaSine-tmp-2023-01-01-macOS.zip)

**Comment by Exink** [comment]
hello, sorry for replying until now.

I've tested the plugin and now it's working again!

I have not encountered any other issue so far.

Thanks a lot!

**Comment by greatest-ape** [comment]
Great! I might ask you to try another build later.

**Comment by greatest-ape** [comment]
@Exink Could you please try out this build?

[OctaSine-tmp-2023-02-12-Windows.zip](https://github.com/greatest-ape/OctaSine/files/10717118/OctaSine-tmp-2023-02-12-Windows.zip)

**Comment by Exink** [comment]
Hello there:
I have tried this version, both for VST and Clap, and it works fine. In fact, I tried to stick with Clap for now.
As a side note, I’ve noticed this plugin has gained some weight! Maybe it needs a visit to the nutritionist? 😊
Tested using Reaper 6.74. I’ve not updated to 6.75, but I hope it works as well. I’ll let you know when it’s done.
Best regards.
Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Joakim ***@***.***>
Enviado: domingo, 12 de febrero de 2023 02:10 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [greatest-ape/OctaSine] Runtime error while using on Reaper (Issue #134)


@Exink<https://github.com/Exink> Could you please try out this build?

OctaSine-tmp-2023-02-12-Windows.zip<https://github.com/greatest-ape/OctaSine/files/10717118/OctaSine-tmp-2023-02-12-Windows.zip>

**Comment by greatest-ape** [comment]
Thanks, great!

I've switched from the glow (OpenGL) backend for iced to the wgpu one, which is likely the reason for increase in size.
