### ISSUE TITLE
Crash with 'Clear' option in Waveform Pro12

### ISSUE THREAD

**Issue by viol8or-alba** [greatest-ape/OctaSine#160]
**Describe the bug**
Attempt to reset to 'init' state using the 'Clear Patch' action crashes the plugin. Note this is using the vst version.

**What did you try to do**
1. Go to 'Actions...'
2. Click on 'Clear'
3. Plugin crashes

**Expected behavior**
Plugin reset to 'init' state

**Log file contents**

```
10:39:42 [INFO] init
10:39:42 [INFO] OS: Windows 10.0.19044 (Windows 10 Home) [64-bit]
10:39:42 [INFO] OctaSine build: v0.8.3 (70f9735) (gl) (vst2)
10:40:15 [ERROR] thread '<unnamed>' panicked at 'already borrowed: BorrowMutError': C:\Users\runneradmin\.cargo\git\checkouts\baseview-9d6c750431f4479e\7001c25\src\win\window.rs:286

```

Interesting that clippy didn't pick this up...

**Software (please complete the following information):**
 - DAW Tracktion Waveform Pro 12
 - OS: Windows 10
 - OctaSine version: 0.8.3

**Additional context**
Please add any other context about the problem here.

**Comment by greatest-ape** [comment]
Thanks.

**Comment by greatest-ape** [comment]
Does this also happen when saving/loading patches? And does it happen when clicking on the values below knobs to input values as text ?

**Comment by viol8or-alba** [comment]
Saving and loading patches (and banks) works fine. Not tried hand editing values yet.

**Comment by greatest-ape** [comment]
Thanks!

If it crashes when hand editing values too, it is likely related to the [tiny](https://docs.rs/tinyfiledialogs/latest/tinyfiledialogs/) dependency, which is used to display "Are you sure?" window prompts when clicking the clear actions as well as for displaying text input windows.

**Comment by viol8or-alba** [comment]
I'll try to give that a shot tonight and see if it crashes. Does tiny have issues? I've have to admit I've never done any GUI stuff with rust...

**Comment by greatest-ape** [comment]
Thanks!

I don't think it has a lot of issues, it has been working pretty well so far. There might also be invalid assumptions made in the baseview windowing library where the panic originated.

**Comment by greatest-ape** [comment]
I'm getting this in REAPER on Windows 10 with both CLAP and VST2 plugins. It happens when clearing patches/banks, but not when setting values or renaming patches, even though those actions also use tinyfiledialogs.

**Comment by viol8or-alba** [comment]
Is there supposed to be a dialog for 'Clear Patch'? Or is this related to the popup menu's window. Dunno if this is in any way related but I notice you can click through that menu. For example, I click 'Rename Patch' and find that I've removed a modulation routing. I now make sure I click on part of the menu that isn't over other controls.

**Comment by greatest-ape** [comment]
Yeah, there is supposed to be one. No, that isn't related, but please open another issue for it :-)

This build replaces it with a custom one and fixes the issue for me. Could you please try it out?

[OctaSine-tmp-2023-04-04-Windows.zip](https://github.com/greatest-ape/OctaSine/files/11152534/OctaSine-tmp-2023-04-04-Windows.zip)

**Comment by viol8or-alba** [comment]
Yup! That fixes it in Waveform. I also gave it a shot in Cakewalk on another machine and it crashes on loading but I've not tried the previous version to see how it behaves. This is just fyi.

**Comment by greatest-ape** [comment]
Great!

Ok.

**Comment by viol8or-alba** [comment]
I've stuck in https://github.com/greatest-ape/OctaSine/issues/168 for the popup issue

**Comment by viol8or-alba** [comment]
Excellent! Thanks for that.
