### ISSUE TITLE
Velocity behavior is unexpected

### ISSUE THREAD

**Issue by kzantow** [greatest-ape/OctaSine#173]
**Describe the bug**
This isn't exactly a bug, but I think it's undesired behavior in many cases: velocity should not affect the MOD OUT amount, at least by default.

If there is a default velocity behavior, it should probably only affect the output level, with the ability to adjust per-operator how much it affects the MOD OUT amount.

**What did you try to do**
Make a patch like this (an attempt to use square waves for percussive noise):
![image](https://user-images.githubusercontent.com/3009477/232241874-59494f11-c5c7-4f90-8bec-76de60a5a8e8.png)

Enter some MIDI notes like this (note the differences in velocity):
![image](https://user-images.githubusercontent.com/3009477/232241950-ec695613-befe-4548-8575-d59287360e4c.png)

**Expected behavior**
The output sounds the same, with different volume levels depending on the velocity.

**Software (please complete the following information):**
 - DAW: Bitwig 4.4.10
 - OS: Windows 10
 - OctaSine version: v0.8.6

**Comment by greatest-ape** [comment]
Yes, I can see your point. Velocity currently affects operator feedback as well as operator volume, which in turn affects modulation output. I could probably add parameters for how much velocity affects:

- final voice volume (after modulation etc), currently not affected
- operator mod out
- operator mix out
- operator feedback

This would mean adding a total of 13 new parameters though, so I would have to think of a good way to present them in the GUI.

**Comment by kzantow** [comment]
I agree you could many different options for this (and these could be expanded to many parameters like envelope attack time), however I'd suggest the most important velocity settings are:

1) final voice volume (the most important -- things could be quieter when playing at low velocities)
2) per-operator mod out (since this is more-or-less how to do filter-like stuff in FM)

I'm not sure if the others are as important as the two mentioned above, which would result in only 4 parameters and be more manageable in the GUI. A suggestion: you _could_ get rid of the target for each operator, since it's duplicated by the matrix. I'll say, though, that I find myself using the target almost exclusively and not the matrix, so that might not be the best...

**Comment by greatest-ape** [comment]
Since the point of this change is to be able to just have final volume be affected, it has to be possible to set the effect on feedback to zero, meaning a parameter for that will be needed too.

Yeah, I added those because someone complained about only being able to set them from the matrix, haha.

A design goal has been to have all knobs/parameters visible on a single surface, but I might have to rethink this.

**Comment by greatest-ape** [comment]
@kzantow What do you think of this? Sensitivity parameters are currently only accessible though the parameter list and not yet through the GUI.

[OctaSine-tmp-2023-05-01-Windows.zip](https://github.com/greatest-ape/OctaSine/files/11368369/OctaSine-tmp-2023-05-01-Windows.zip)

**Comment by kzantow** [comment]
@greatest-ape I had a play with this... I think the defaults should be 100% for the "Mix out sensitivity" and 0% for everything else, but overall this definitely helps. For example this patch (play F1) is close to a ride cymbal (obviously remove the `.txt` extension)
[octasine-quick-ride.fxp.txt](https://github.com/greatest-ape/OctaSine/files/11377979/octasine-quick-ride.fxp.txt)

**Comment by greatest-ape** [comment]
Thanks for trying it out!

Yeah, those would be sensible defaults. Currently, they have to have those defaults for backwards compatibility, but I might be able to rewrite some stuff to change that.

I was just going to upload a build exposing the parameters in the GUI. Please try it out if you want to: 
[OctaSine-tmp-2023-05-02-Windows.zip](https://github.com/greatest-ape/OctaSine/files/11378016/OctaSine-tmp-2023-05-02-Windows.zip)

**Comment by kzantow** [comment]
I tried this but I don't see anything other than the VOL VS control, and without having the others default to 0, it still seems to have the unexpected behavior. Am I missing something?

**Comment by greatest-ape** [comment]
Ah, there are new buttons on the right side to toggle showing those controls, but they might be too easy to miss.

**Comment by kzantow** [comment]
Oh, I see. If I could offer a suggestion how to integrate these "extras" into the GUI: would it make sense to just have a single button, maybe near the top (or in the bottom right section(s)) maybe labeled something like "More", which toggles _all_ the extra controls at once? And for these, I might put them in the panels with MIX OUT / FEEDBACK instead of the envelope, since they are more directly related to the behavior of those controls.

**Comment by greatest-ape** [comment]
Having a single button is a good idea and would save horizontal space. But I think users might want to have the new knobs and feedback/mod out visible at the same time to tune both?

**Comment by greatest-ape** [comment]
Build with single button to toggle change of controls for all operators: [OctaSine-tmp-2023-05-04-Windows.zip](https://github.com/greatest-ape/OctaSine/files/11401795/OctaSine-tmp-2023-05-04-Windows.zip)

**Comment by greatest-ape** [comment]
Support has been merged: https://github.com/greatest-ape/OctaSine/pull/175
