### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by Twfstunna** [greatest-ape/OctaSine#185]
**Describe the bug**

**What did you try to do**

**Expected behavior**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Log file contents**
Please include the contents of the OctaSine log file (`OctaSine.log`). Its location depends on your operating system (replace __Alice__ with your username):
- _On macOS_: /Users/__Alice__/Library/Application Support/com.OctaSine.OctaSine/OctaSine.log (the file can be opened with TextEdit)
- _On Windows_: C:\\Users\\__Alice__\\Documents\\OctaSine\\OctaSine.log (the file can be opened with Notepad)
- _On Linux_: /home/__Alice__/.config/octasine/OctaSine.log (the file can be opened with a plain text editor)

```
Please replace this text with the log file contents.

If there is a lot of text, please attach the file instead.
```

**Software (please complete the following information):**
 - DAW [e.g. Ableton Live Suite 11]
 - OS: [e.g. Windows 10, macOS 10.15] (can be skipped if present in the log file above)
 - OctaSine version [e.g. 0.8.2] (can be skipped if present in the log file above). It can be displayed by hovering over the Info button in the bottom right corner of the user interface.

**Additional context**
Please add any other context about the problem here.

**Comment by greatest-ape** [comment]
You're going to have to give some more information than this..
