### ISSUE TITLE
OctaSine defaults to first patch upon reloading project

### ISSUE THREAD

**Issue by talktopag** [greatest-ape/OctaSine#186]
Using OctaSine v0.9 + Renoise V3.4.3 on Linux Mint 21.2. 

When reloading a saved project, all of the patches within a bank associated with an OctaSine instance are reloaded again as expected, however each instance of OctaSine defaults to the first patch in the bank, rather than the selected patch at the time of saving the project.

Current workaround is to not use a patch bank, but rather just load the required patch into the first slot of each instance, however this is likely unexpected behaviour and I have raised as a potential bug for your consideration.

Many thanks for this awesome software, and please let me know if I can provide any more useful info.

**Comment by SpotlightKid** [comment]
I can confirm that this happens in Ardour on Linux as well. The workaround I use is the same as described above.

**Comment by greatest-ape** [comment]
Thanks! I've merged a fix that will be included in the next release.
