### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by grainmagic** [greatest-ape/OctaSine#19]
Would it be possible to add a window resizing option? The plugin window can be a little too big for smaller screens.

**Comment by greatest-ape** [comment]
I think window resizing will be too difficult. I could however decrease the size of the window and all components. Would a size like in this screenshot work for you?

![screenshot](https://user-images.githubusercontent.com/17945069/125602177-a070d1af-119e-42f0-88bd-5cb07fcf17f1.png)

**Comment by grainmagic** [comment]
I think this could work well. I hope it won't be too hard to implement.

**Comment by greatest-ape** [comment]
I've made the window smaller (904 x 866 pixels). The changes are on the master branch and will be part of the next release. Do you think this is small enough?

**Comment by grainmagic** [comment]
Yes!

**Comment by greatest-ape** [comment]
Ok, great!
