### ISSUE TITLE
Some problem with graphic interface in Renoise [osx 10.13.6]

### ISSUE THREAD

**Issue by KlashKontakt** [greatest-ape/OctaSine#23]
Hello!

screenshot :
https://disk.yandex.ru/i/mJCTwR2vdD2fww

 - OctaSine version [e.g. 0.5.3]. 
 - DAW [Renoise 3.3.2]
 - OS: [macOS 10.13.6]

Some problem with graphic 

Thnx for your work!

**Comment by KlashKontakt** [comment]
Octasine.log

09:02:04 [INFO] init
09:02:04 [INFO] OS: Mac OS 10.13.6 [64-bit]
09:02:04 [INFO] OctaSine build: v0.5.3 (35957f4) (wgpu)
09:02:04 [INFO] Couldn't load settings: No such file or directory (os error 2)
09:02:04 [WARN] Unknown decoration ColMajor
09:02:04 [WARN] Unknown decoration MatrixStride
09:02:04 [WARN] Treating VertexIndex as unsigned

**Comment by greatest-ape** [comment]
@KlashKontakt Could you please try with the latest release? https://github.com/greatest-ape/OctaSine/releases/tag/v0.5.4

**Comment by greatest-ape** [comment]
@KlashKontakt I saw your other issue, thanks. Was this GUI issue fixed with version 0.5.4?

**Comment by greatest-ape** [comment]
I'm closing this issue since it seems like the issue was resolved.
