### ISSUE TITLE
Indicate whether Windows build is 32-bit or 64-bit

### ISSUE THREAD

**Issue by bhagerty** [greatest-ape/OctaSine#24]
This is not a bug, but the issue tracker won't let me create anything but a bug report. I just suggest indicating whether the Windows build is 64-bit or 32-bit. I assume it's 64-bit, but I'd prefer not to assume.

**Comment by greatest-ape** [comment]
Hey, thanks. It is indeed a 64-bit build. I updated the website to reflect that. OctaSine actually won't even run on 32-bit CPUs since it uses double precision floats.
