### ISSUE TITLE
Note off issue

### ISSUE THREAD

**Issue by mbrowne999** [greatest-ape/OctaSine#25]
Nektar Impact GX 25 Mini keyboard is sending note off, but Octasine notes are stuck.

**Comment by greatest-ape** [comment]
@mbrowne999 Latest version 0.6.0 should have fixed this issue. Could you please try it out?

**Comment by mbrowne999** [comment]
Works great.  Thanks for letting me know.  I like the minimal interface and sound abilities!
-mb


    On Saturday, January 8, 2022, 08:33:59 AM PST, Joakim Frostegård ***@***.***> wrote:  
 
 


@mbrowne999 Latest version 0.6.0 should have fixed this issue. Could you please try it out?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by greatest-ape** [comment]
Great! And thanks.
