### ISSUE TITLE
Buffer size issues in FL Studio and Savihost

### ISSUE THREAD

**Issue by bryc** [greatest-ape/OctaSine#26]
Plugin exhibits constant buffer underruns or audible crackles in the audio output.

This can only be fixed in FL Studio by enabling two processing options: **Use fixed size buffers** and **Process maximum size buffers**.  No possible workaround in Savihost.

OS: Win10
DAW: FL Studio 12.5.1

**Comment by greatest-ape** [comment]
Thanks. I added a mention of the fix on the official website. Unfortunately, I probably won't have time to have a look at rewriting the buffer logic for a while, though.

**Comment by greatest-ape** [comment]
@bryc Latest version 0.6.0 should have fixed this issue. Could you please try it out?

**Comment by bryc** [comment]
Yep, confirmed to be fixed in FL Studio 12/20 now.

**Comment by greatest-ape** [comment]
Great, thanks!

And nice track.
