### ISSUE TITLE
Build fails: "failed to resolve patches for `https://github.com/RustAudio/baseview`"

### ISSUE THREAD

**Issue by 190n** [greatest-ape/OctaSine#28]
**Describe the bug**

When I tried to build OctaSine, cargo threw an error having to do with the baseview dependency.

**What did you try to do**

1. Clone the OctaSine repository
2. Attempt to build with `cargo +nightly build --release --features simd -p octasine_vst2_plugin` (building without SIMD fails in the same way)

Cargo output:

```
    Updating git repository `https://github.com/greatest-ape/baseview.git`
error: failed to resolve patches for `https://github.com/RustAudio/baseview`

Caused by:
  failed to load source for dependency `baseview`

Caused by:
  Unable to update https://github.com/greatest-ape/baseview.git?branch=octasine#780edcee

Caused by:
  object not found - no match for id (780edcee7e214634992523ddb51a5f7d371791ad); class=Odb (9); code=NotFound (-3)
```

I eventually built baseview myself (using the same fork and branch specified in Cargo.toml) and pointed Cargo at the directory where I had built the patched version, instead of the version on GitHub. I think this would've worked, except I ran into another issue with iced_baseview.

**Expected behavior**

It compiles OctaSine.

**Software (please complete the following information):**
 - OctaSine version: git master branch (e53551a)
 - OS: Arch Linux

**Comment by greatest-ape** [comment]
@190n Could you please pull from master and try again? I just merged some work involving dependency changes.

**Comment by 190n** [comment]
It works now, thank you! Closing.
