### ISSUE TITLE
Some problem with buffer synchronize 

### ISSUE THREAD

**Issue by KlashKontakt** [greatest-ape/OctaSine#30]
Greetings! 

Thanks for the new release and for the fixes! 
In the new version, I noticed some problem with synchronizing notes when the buffer increases. Below are screenshots with the minimum and maximum buffer. Thank you

small buffer
<img width="1305" alt="SNHR_2" src="https://user-images.githubusercontent.com/87890552/146906603-00c905ff-cc84-4a17-8b07-e7b6f936b8ab.png">

big buffer
<img width="1340" alt="SNHR" src="https://user-images.githubusercontent.com/87890552/146906623-4361d652-6c12-4ef6-8951-8a99bd7d4063.png">

 - OctaSine version 0.5.4 
 - DAW Renoise 3.3.2
 - OS:  macOS 10.13.6

Thnx for your work and have nice day!

**Comment by greatest-ape** [comment]
Thanks, this is interesting, I'll have a look.

**Comment by greatest-ape** [comment]
@KlashKontakt what are the sizes of the small/big buffers?

**Comment by greatest-ape** [comment]
@KlashKontakt Latest version 0.6.0 should have fixed this issue. Could you please try it out?

**Comment by KlashKontakt** [comment]
Hello!!!! BIG THNX!!!! Working good!   Testing testing testing!!!!!  Have nice day! Alexey! 08.01.2022, 19:33, "Joakim Frostegård" ***@***.******@***.*** Latest version 0.6.0 should have fixed this issue. Could you please try it out?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by KlashKontakt** [comment]
new  version 0.6 working good thnx!!!!

**Comment by greatest-ape** [comment]
Great! And thanks for reporting the bug.
