### ISSUE TITLE
help with downloading

### ISSUE THREAD

**Issue by 24t2t2t24** [greatest-ape/OctaSine#43]
Hi, I tried to follow the instructions and follow the terminal part. I put In my password, which I know, but it keeps saying sorry, try again what do I do please let me know

**Comment by greatest-ape** [comment]
Hello @24t2t2t24,

Are you on macOS?

**Comment by 24t2t2t24** [comment]
yes

**Comment by greatest-ape** [comment]
@24t2t2t24 OK. Is your user an admin user?
