### ISSUE TITLE
NoteOff events don't end Decay phase

### ISSUE THREAD

**Issue by bryc** [greatest-ape/OctaSine#74]
**Describe the bug**
The Decay phase of the envelope does not end with a NoteOff event.

**Expected behavior**
A NoteOff event should terminate the Decay phase and immediately begin the Release phase, at its current level.

**What did you try to do**
I created two functionally identical patches ([FXP patches here if needed](https://github.com/greatest-ape/OctaSine/files/8923458/patches.zip)) in OctaSine 0.6, which is unaffected by this issue, and in OctaSine 0.7, which is affected by this issue:

It uses a relatively long decay rate, but a relatively short release rate. While playing a "Clavinet" type sequence, which utilizes very short notes, it exhibits the issue clearly:

https://user-images.githubusercontent.com/1408749/174196304-76af0799-f72f-4620-a85b-65de68b15d7d.mp4

**Software (please complete the following information):**
 - OctaSine version: v0.7.0 (b05fcf1) (gl).
 - DAW: FL Studio 12 x64.
 - OS: Windows 10.0.19042 (Windows 10 Pro) [64-bit]

**Comment by greatest-ape** [comment]
Thanks for the detailed report.

**Comment by greatest-ape** [comment]
@bryc This release should fix the issue. What do you think? Could you please also check what you think of how note off events are now handled during the attack phase?

I've also reintroduced master frequency and volume parameters as lfo targets in this build :-)

[OctaSine-tmp-2022-07-24-macOS-Intel.zip](https://github.com/greatest-ape/OctaSine/files/9176803/OctaSine-tmp-2022-07-24-macOS-Intel.zip)
[OctaSine-tmp-2022-07-24-Windows.zip](https://github.com/greatest-ape/OctaSine/files/9176805/OctaSine-tmp-2022-07-24-Windows.zip)

**Comment by bryc** [comment]
A bit late, but looks good so far! No issues. Attack phase seems fine, it goes directly to release stage on note off. I think I can close this issue.

**Comment by bryc** [comment]
Yep, nothing standing out so far, made a nice preset after realizing some of the ratios were perfect fourths/fifths 😄:

https://user-images.githubusercontent.com/1408749/181611295-5f714278-c2a1-4244-aa30-06b7650023d9.mp4

Here's the preset if you want to have a look: [Fourth Wall v07.zip](https://github.com/greatest-ape/OctaSine/files/9213263/Fourth.Wall.v07.zip)

**Comment by greatest-ape** [comment]
Great!

Sweet patch :-)

**Comment by greatest-ape** [comment]
I might want to include your patch as a preset. Would you be fine with it, under the AGPL 3.0 license?

**Comment by bryc** [comment]
> I might want to include your patch as a preset. Would you be fine with it, under the AGPL 3.0 license?

Is there some reason they can't be `CC BY-NC-SA 4.0` (which I'd be fine with)? My only concern is that presets posted to sites like Archive.org or AudioBomb usually only allow CC as a license option, since presets and similar media aren't 'code'.

But if AGPLv3 is a requirement, I'd be fine with that too. Just complicates the matter if I had already had it on Archive.org under CC. In general, feel free to use it with attribution. 👍

**Comment by greatest-ape** [comment]
Ok, nice! Yeah, it would probably be fine. We’ll see if it fits in with some other patches I have planned :-)
