### ISSUE TITLE
OpenGL error on the vst and crashing the daw

### ISSUE THREAD

**Issue by levyonthecrack** [greatest-ape/OctaSine#82]
**Describe the bug**
clicking the vst causes ableton to crash.

**What did you try to do**
1. go to vsts
2. click on octasine vst

**Expected behavior**
expected the vst to load but nothing happens, it just crashes ableton.

**Screenshots**

**Software:**
 - OctaSine 0.7.0 (4ea0e33) (gl)
 - DAW: Ableton Live Suite 11
 - OS: Windows 10.0.19044 

**Log file contents**
17:25:13 [INFO] init
17:25:13 [INFO] OS: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
17:25:13 [INFO] OctaSine build: v0.7.0 (4ea0e33) (gl)
17:25:13 [ERROR] thread '<unnamed>' panicked at 'Could not create OpenGL context: CreationFailed(())': C:\Users\runneradmin\.cargo\git\checkouts\baseview-9d6c750431f4479e\b371263\src\win\window.rs:519

**Comment by greatest-ape** [comment]
Thanks!

Do you know what graphics card you’re using and if you have the latest drivers for it?

**Comment by levyonthecrack** [comment]
Hey bro! Thanks for answering!

My graphic cards are integrated, its pretty old but ill try to get a better
one next month, the card is a i5 650 3.20ghz

I really want to test your plugin because im a big fan of FM Synthesis and
monomachine, i had a lot of problems involving opengl in the past too, but
i can still have compatibility with other plugins.

Sorry if i said something wrong, english is not my first english :)

Em qua., 17 de ago. de 2022 07:17, Joakim Frostegård <
***@***.***> escreveu:

**Comment by levyonthecrack** [comment]
Yes latest drivers too.

Em qua., 17 de ago. de 2022 07:17, Joakim Frostegård <
***@***.***> escreveu:

**Comment by greatest-ape** [comment]
Ok!

It seems like your iGPU is [this one](https://www.techpowerup.com/gpu-specs/hd-graphics.c2028), which only supports OpenGL 2.1. At least version 3.0 is required for OctaSine because it’s the lowest one supported by [iced_glow](https://docs.rs/iced_glow/latest/iced_glow/), and I don’t foresee this changing, unfortunately :/

**Comment by levyonthecrack** [comment]
Oh, its okay! ill get a better igpu soon, thanks! :)
