### ISSUE TITLE
Feature request: 1-shot LFO retain the end value

### ISSUE THREAD

**Issue by kzantow** [greatest-ape/OctaSine#86]
**Describe the bug**
After a 1-shot LFO completes, it appears to send a modulation amount of 0 (or just no longer affect modulation). For example, if one wants to make a kick drum (or other similarly pitched percussive sounds), the only viable option seems to be using LFO with REV SAW. This is ok if you time it such that the entire time of the LFO is shorter than the time of the note. But this becomes especially more problematic if you want to have multiple REV SAW LFOs affecting the pitch for getting a more punchy/less linear pitch sound, for example. When the shorter LFO ends, it does not continue to send  the last value (in this case, I presume is `-1`), but instead stops affecting the sound, resulting in a discontinuity in pitch. Take an LFO like this:
![image](https://user-images.githubusercontent.com/3009477/187031174-21b8733c-e9dd-46da-af20-690190ecbb20.png)
Results in a waveform like this:
![image](https://user-images.githubusercontent.com/3009477/187031199-a2efe4a9-49b3-4307-96a9-445c8d14b565.png)
Where in the middle you can see a discontinuity where the LFO ended.

**What did you try to do**
- (Like the picture) select OP 1 FREQ FREE, REV SAW, ratio 2, 1 shot
- Play a note longer than the length of the LFO

**Expected behavior**
The end of the LFO retains the value, so there isn't a discontinuity in the modulation.

**Screenshots**
(added above)

**Software (please complete the following information):**
 - OctaSine version: v0.7.0
 - DAW: Bitwig 4.3.4
 - OS: Windows 10

P.S. This seems like a very nice, straightforward synth -- thanks for making it!

**Comment by greatest-ape** [comment]
Yes, this would probably make sense.

> P.S. This seems like a very nice, straightforward synth -- thanks for making it!

Thanks!

**Comment by greatest-ape** [comment]
I’ve merged a fix, so I’m closing the issue :-)
