### ISSUE TITLE
Feature request: operator square waves

### ISSUE THREAD

**Issue by kzantow** [greatest-ape/OctaSine#87]
**Describe the feature**
It would be great to have square waves available as an option for the operators. One reason for this is that FM using square waves and feedback can actually make much nicer cymbal sounds than noise - a prime example of this is ride cymbals that have a bit of tonality, but almost all uses of noise can benefit from this method to get brighter noise.

(Also, additionally having saw and triangle waves opens up the sound palate in very interesting ways)

**Comment by greatest-ape** [comment]
This is something that I might look into eventually, but not right now.

**Comment by greatest-ape** [comment]
I've implemented all three wave types, they will be merged and released eventually :-)

**Comment by kzantow** [comment]
That's great! @greatest-ape  :) I can't wait for the update! I hope it drops while your synth is part of the [One-Synth-Challenge this month](https://sites.google.com/site/kvrosc/2023/osc-170-octasine)!

**Comment by greatest-ape** [comment]
They have now been released in v0.8.5 :-)
