### ISSUE TITLE
Parameter automation not working in Bitwig

### ISSUE THREAD

**Issue by kzantow** [greatest-ape/OctaSine#90]
**Describe the feature**
It appears currently there are no parameters exposed for automation. It would be great to add parameter automation for most parameters, as it makes sense for parameters like like: levels, decay/release times, operator frequencies (selecting LFO shape might not make sense, for example).

In case this is a bug:

**Software (please complete the following information):**
 - OctaSine version: custom build from #85 
 - DAW: Bitwig 4.3.4
 - OS: Windows 10

**Comment by greatest-ape** [comment]
Hmm, all parameters should already be automatable. Automating works for me in a variety of DAWs.

**Comment by kzantow** [comment]
I tried this in REAPER and you're right, parameters show up fine there... this seems to be a Bitwig issue (also tried it on my M1 Mac with the same problem). I'll see if I can possibly figure anything out to help/fix. My rust skills are pretty rudimentary, however 😢

**Comment by greatest-ape** [comment]
That’s weird. I just downloaded the Bitwig demo and the parameters don’t appear to me either.

**Comment by SpotlightKid** [comment]
Parameter also does not work in Carla (Manjaro Linux). When I asked its author *falkTX* about it, he said that for each automatable parameter, the "plugin needs to return 1 to effCanBeAutomated opcode".

I don't know enough Rust to check whether that's the case. But it would probably be a good thing to check.

**Comment by greatest-ape** [comment]
@SpotlightKid Thanks a lot, this helped me solve the issue. There was indeed a bug in the logic telling the host which parameters are automatable. The fix has been merged into master and will be part of the next release.

**Comment by SpotlightKid** [comment]
An that's why I love open source! :) Thank! Looking forward to the next release.
